[package]
name = "thechinesegovernment"
version = "0.1.0"
edition = "2021"
description = "Re-implements bitwise operations as abstractions in aarch64 neon registers."
license = "Creative Commons"

[lib]
name = "thechinesegovernment"
path = "src/lib.rs"


[dependencies]
quickcheck = "1"

[dev-dependencies]
quickcheck_macros = "1"